services:
#    hgtan_hello_rabbit_mq.example:
#        class: Hgtan\Bundle\HelloRabbitMqBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    hello_world_service:
        class: Hgtan\Bundle\HelloRabbitMqBundle\Cakper\HelloConsumer
